export const FETCH_PRODUCT_REQUEST = 'FETCH_PRODUCT_REQUEST';
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS';
export const FETCH_PRODUCT_ERROR = 'FETCH_PRODUCT_ERROR';
export const FETCH_PRODUCT_CANCEL = 'FETCH_PRODUCT_CANCEL';

// FILTER
export const FILTER_REQUEST = 'FILTER_REQUEST';
export const IS_FILTERED = 'IS_FILTERED';
export const CLEAR_FILTER = 'CLEAR_FILTER';
export const SHOW_ALERT = 'SHOW_ALERT';
export const HIDE_ALERT = 'HIDE_ALERT';